[package]
name = "sqlite_book_db"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
palette = "0.7.6"
ratatui = "0.29.0"

[dependencies.rusqlite]
version = "0.32.1"
features = ["bundled"]
