event_open_splash_screen = "Open splash screen"
event_open_file_explorer_screen = "Open file explorer"
event_open_db_schema_screen = "Open database schema"
event_open_db_table_screen = "Open database table"
event_open_create_new_file_screen = "Create new database file"
event_open_options_screen = "Options"
event_open_insert_row_popup = "Insert new row"
event_open_delete_row_popup = "Delete row"
event_open_insert_table_popup = "Insert new table"
event_open_delete_table_popup = "Delete table"
event_close_popup = "Close popup"
event_open_quit_app_popup = "Quit application"
event_quit_app_confirm = "Confirm quit"
event_move_up_primary = "Move up in primary"
event_move_down_primary = "Move down in primary"
event_move_up_secondary = "Move up in secondary"
event_move_down_secondary = "Move down in secondary"
event_execute_action = "Execute action"
event_toggle_option = "Toggle option"
event_file_explorer_select = "Select file/folder"
event_file_explorer_back = "Go back"
event_switch_to_edit = "Switch to edit mode"
event_switch_to_browse = "Switch to browse mode"
screen_splash_db_placeholder = "None"
screen_splash_table_placeholder = "None"
screen_splash_application_name = "Database TUI app"
screen_splash_loaded_db = "Loaded Database"
screen_splash_loaded_table = "Loaded Table"
screen_file_explorer_title = "Explorer"
screen_file_explorer_current_location = "Currently in"
screen_file_explorer_file_folder_header = "File/Folder"
screen_file_explorer_size_header = "Size"
screen_file_explorer_date_created_header = "Date created"
screen_file_explorer_dir = "DIR"
screen_file_explorer_dir_read_error = "Error reading directory"
screen_db_schema_no_db_found = "No Database found"
screen_db_schema_current_db = "Current Database"
screen_db_table_current_table = "Current Table"
screen_db_table_table_placeholder = "None"
screen_options_title = "Options"
screen_options_color_schemes = "Color schemes"
screen_options_metadata_in_table = "Display column metadata in table view"
screen_options_metadata_in_insert = "Display column metadata in insert view"
screen_options_render_info = "Render info block on screens and popups"
screen_options_info_block_height = "Enter height in the information block in lines"
popup_quit_confirmation = "Are you sure you want to quit?"
popup_no_db_loaded = "No Database file loaded"
popup_error_title = "Error"
table_list_title = "Tables"
table_list_emtpy_placeholder = "Emtpy schema"
table_list_name_header = "Name"
table_list_rows_header = "Rows"
table_list_type_header = "Type"
table_list_view_element = "View"
table_list_table_element = "Table"
column_list_title = "Columns"
column_list_emtpy_placeholder = "No Columns"
column_list_name_header = "Name"
column_list_type_header = "Type"
column_list_constraints_header = "Constraints"
column_list_unknown_fk_ref = "Unknown"
info_block_title = "Info"

mode_current_mode = "Mode"

widget_selectable_field_highlight_marker = "*"
widget_selectable_field_on_value = "ON"
widget_selectable_field_off_value = "OFF"

sql_pk_constraint = "PK"
sql_unique_constraint = "UNIQUE"
sql_not_null_constraint = "NOT NULL"
sql_fk_constraint = "FK"

invalid_utf_8 = "Invalid UTF_8"
not_available = "N/A"
bytes = "Bytes"
app_datetime_format = "%Y-%m-%d %H:%M:%S"
