open_splash_screen = "Open splash screen"
open_file_explorer_screen = "Open file explorer"
open_db_schema_screen = "Open database schema"
open_db_table_screen = "Open database table"
open_create_new_file_screen = "Create new database file"
open_options_screen = "Options"
open_insert_row_popup = "Insert new row"
open_delete_row_popup = "Delete row"
open_insert_table_popup = "Insert new table"
open_delete_table_popup = "Delete table"
close_popup = "Close popup"
open_quit_app_popup = "Quit application"
quit_app_confirm = "Confirm quit"
move_up_primary = "Move up in primary"
move_down_primary = "Move down in primary"
move_up_secondary = "Move up in secondary"
move_down_secondary = "Move down in secondary"
execute_action = "Execute action"
toggle_option = "Toggle option"
file_explorer_select = "Select file/folder"
file_explorer_back = "Go back"
switch_to_edit = "Switch to edit mode"
switch_to_browse = "Switch to browse mode"
